---
- name: Install Packages
  hosts: '{{ target_hosts }}'
  become: yes
  become_user: dvanwedd
  connection: local
  tasks:
    - name: Install Screen
      yum:
        name: screen
        state: latest
